language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
gemfile:
  - gemfiles/on_rails_23x.gemfile
  - gemfiles/on_rails_30x.gemfile
  - gemfiles/on_rails_31x.gemfile
  - gemfiles/on_rails_32x.gemfile